### ISSUE TITLE
Sent Schedule Messages bug

### ISSUE THREAD

**Issue by gemfarmer** [18F/dolores-landingham-bot#130]
If you go to the [sent scheduled messages view](https://dolores-app.18f.gov/sent_scheduled_messages), the app errors out. The logs are below. I'm pretty sure this because the view is looking for the `slack_username` of an employee that no longer has a record. The `sent_scheduled_messsages` model [delegates](https://github.com/18F/dolores-landingham-bot/blob/master/app/models/sent_scheduled_message.rb#L11) finding an employee via its `employee_id` field. 

Sooo we need some way to catch this and not display the record if the employee has been deleted. Or display the record without an associated `slack_username`.

```
Rendered sent_scheduled_messages/index.html.erb within layouts/application (146.4ms)
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    | Completed 500 Internal Server Error in 147ms (ActiveRecord: 68.9ms)
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    | 
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    | ActionView::Template::Error (SentScheduledMessage#slack_username delegated to employee.slack_username, but employee is nil: #<SentScheduledMessage id: 941, created_at: "2016-01-11 20:13:37", updated_at: "2016-01-11 20:13:37", employee_id: 52, error_message: "", message_body: "From your coworker *Liz Goodman*: \"If you get a tr...", scheduled_message_id: 41, sent_on: "2016-01-11", sent_at: "2000-01-01 20:13:37">):
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |     23: 
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |     24:   <% @sent_scheduled_messages.each do |sent_message| %>
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |     25:     <tr>
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |     26:       <td><%= sent_message.slack_username %></td>
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |     27:       <td><%= sent_message.sent_on %></td>
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |     28:       <td><%= display_local_time_zone(sent_message) %></td>
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |     29:       <td><%= truncate(sent_message.message_body, length: 50, separator: ' ') %></td>
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |   app/models/sent_scheduled_message.rb:11:in `rescue in slack_username'
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |   app/models/sent_scheduled_message.rb:11:in `slack_username'
```

**Comment by jessieay** [comment]
we should add a `dependent: :destroy` on sent scheduled messages for a deleted employee.  can use paranoia to make sure we don't *actually* delete data https://github.com/rubysherpas/paranoia

**Comment by gemfarmer** [comment]
@jessieay I like it. :+1:

**Comment by jessieay** [comment]
im working on this now

**Comment by jessieay** [comment]
This is fixed and deployed! https://dolores-app.18f.gov/sent_scheduled_messages
